version: '3.3'

services:
  wiki:
    container_name: wiki
    build:
      context: ./core
    command: gunicorn core.wsgi --bind 0.0.0.0:8000
    volumes:
      - ./core:/usr/src/app
      - static_volume:/app/static/
      - media_volume:/app/media/
    expose:
      - "8000"
    env_file:
      - ./core/.env

  nginx:
    image: nginx
    container_name: nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/home/app/static/
      - media_volume:/home/app/media/
    depends_on:
      - wiki

volumes:
  static_volume:
  media_volume: